// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_ORDERSORMG_MSGSERIALIZATION_H_
#define FLATBUFFERS_GENERATED_ORDERSORMG_MSGSERIALIZATION_H_

#include "flatbuffers/flatbuffers.h"

namespace MsgSerialization {

struct Order_SOR_Market;
struct Order_SOR_MarketBuilder;

struct Order_SOR_Market FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef Order_SOR_MarketBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_USER_ID = 4,
    VT_SERVER_ID = 6,
    VT_MARKET_VENUE_ID = 8,
    VT_SYMBOL = 10,
    VT_PRICE = 12,
    VT_QTY = 14
  };
  const flatbuffers::String *user_id() const {
    return GetPointer<const flatbuffers::String *>(VT_USER_ID);
  }
  const flatbuffers::String *server_id() const {
    return GetPointer<const flatbuffers::String *>(VT_SERVER_ID);
  }
  int32_t market_venue_id() const {
    return GetField<int32_t>(VT_MARKET_VENUE_ID, 0);
  }
  const flatbuffers::String *symbol() const {
    return GetPointer<const flatbuffers::String *>(VT_SYMBOL);
  }
  float price() const {
    return GetField<float>(VT_PRICE, 0.0f);
  }
  float qty() const {
    return GetField<float>(VT_QTY, 0.0f);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_USER_ID) &&
           verifier.VerifyString(user_id()) &&
           VerifyOffset(verifier, VT_SERVER_ID) &&
           verifier.VerifyString(server_id()) &&
           VerifyField<int32_t>(verifier, VT_MARKET_VENUE_ID) &&
           VerifyOffset(verifier, VT_SYMBOL) &&
           verifier.VerifyString(symbol()) &&
           VerifyField<float>(verifier, VT_PRICE) &&
           VerifyField<float>(verifier, VT_QTY) &&
           verifier.EndTable();
  }
};

struct Order_SOR_MarketBuilder {
  typedef Order_SOR_Market Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_user_id(flatbuffers::Offset<flatbuffers::String> user_id) {
    fbb_.AddOffset(Order_SOR_Market::VT_USER_ID, user_id);
  }
  void add_server_id(flatbuffers::Offset<flatbuffers::String> server_id) {
    fbb_.AddOffset(Order_SOR_Market::VT_SERVER_ID, server_id);
  }
  void add_market_venue_id(int32_t market_venue_id) {
    fbb_.AddElement<int32_t>(Order_SOR_Market::VT_MARKET_VENUE_ID, market_venue_id, 0);
  }
  void add_symbol(flatbuffers::Offset<flatbuffers::String> symbol) {
    fbb_.AddOffset(Order_SOR_Market::VT_SYMBOL, symbol);
  }
  void add_price(float price) {
    fbb_.AddElement<float>(Order_SOR_Market::VT_PRICE, price, 0.0f);
  }
  void add_qty(float qty) {
    fbb_.AddElement<float>(Order_SOR_Market::VT_QTY, qty, 0.0f);
  }
  explicit Order_SOR_MarketBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<Order_SOR_Market> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Order_SOR_Market>(end);
    return o;
  }
};

inline flatbuffers::Offset<Order_SOR_Market> CreateOrder_SOR_Market(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::String> user_id = 0,
    flatbuffers::Offset<flatbuffers::String> server_id = 0,
    int32_t market_venue_id = 0,
    flatbuffers::Offset<flatbuffers::String> symbol = 0,
    float price = 0.0f,
    float qty = 0.0f) {
  Order_SOR_MarketBuilder builder_(_fbb);
  builder_.add_qty(qty);
  builder_.add_price(price);
  builder_.add_symbol(symbol);
  builder_.add_market_venue_id(market_venue_id);
  builder_.add_server_id(server_id);
  builder_.add_user_id(user_id);
  return builder_.Finish();
}

inline flatbuffers::Offset<Order_SOR_Market> CreateOrder_SOR_MarketDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const char *user_id = nullptr,
    const char *server_id = nullptr,
    int32_t market_venue_id = 0,
    const char *symbol = nullptr,
    float price = 0.0f,
    float qty = 0.0f) {
  auto user_id__ = user_id ? _fbb.CreateString(user_id) : 0;
  auto server_id__ = server_id ? _fbb.CreateString(server_id) : 0;
  auto symbol__ = symbol ? _fbb.CreateString(symbol) : 0;
  return MsgSerialization::CreateOrder_SOR_Market(
      _fbb,
      user_id__,
      server_id__,
      market_venue_id,
      symbol__,
      price,
      qty);
}

inline const MsgSerialization::Order_SOR_Market *GetOrder_SOR_Market(const void *buf) {
  return flatbuffers::GetRoot<MsgSerialization::Order_SOR_Market>(buf);
}

inline const MsgSerialization::Order_SOR_Market *GetSizePrefixedOrder_SOR_Market(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<MsgSerialization::Order_SOR_Market>(buf);
}

inline bool VerifyOrder_SOR_MarketBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<MsgSerialization::Order_SOR_Market>(nullptr);
}

inline bool VerifySizePrefixedOrder_SOR_MarketBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<MsgSerialization::Order_SOR_Market>(nullptr);
}

inline void FinishOrder_SOR_MarketBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<MsgSerialization::Order_SOR_Market> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedOrder_SOR_MarketBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<MsgSerialization::Order_SOR_Market> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace MsgSerialization

#endif  // FLATBUFFERS_GENERATED_ORDERSORMG_MSGSERIALIZATION_H_
